"""
Django settings for routechoices project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from .settings import *  # noqa

DEBUG = False
SITE_ID = 1

SHORTCUT_BASE_URL = "http://www.routechoices.dev/r/"
