# Generated by Django 4.0.3 on 2022-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_club_description_alter_event_map_title_and_more"),
        ("invitations", "0003_auto_20151126_1523"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="e-mail address"),
        ),
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("email", "club")},
        ),
    ]
