# Generated by Django 4.0.3 on 2022-06-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_club_description_alter_event_map_title_and_more"),
        ("invitations", "0004_invitation_club_alter_invitation_email_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("email", "club", "accepted")},
        ),
    ]
