# Generated by Django 4.0.1 on 2022-01-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="short_name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="device",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
