# Generated by Django 4.0.1 on 2022-02-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_competitor_short_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="send_interval",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
