# Generated by Django 2.1.5 on 2019-02-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20190201_0757"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competitor",
            options={
                "ordering": ["start_time", "name"],
                "verbose_name": "competitor",
                "verbose_name_plural": "competitors",
            },
        ),
    ]
