# Generated by Django 4.0.3 on 2022-04-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_devicearchivereference"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="battery_level",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
