# Generated by Django 2.1.5 on 2019-02-03 20:44

from django.db import migrations, models

import routechoices.lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20190203_1900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="slug",
            field=models.CharField(
                help_text="This the text that will be used in the urls of your events",
                max_length=50,
                unique=True,
                validators=[routechoices.lib.validators.validate_nice_slug],
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="corners_coordinates",
            field=models.CharField(
                help_text="Latitude and longitude of map corners separated by commas in following order Top Left, Top right, Bottom Right, Bottom left. eg: 60.519,22.078,60.518,22.115,60.491,22.112,60.492,22.073",
                max_length=255,
                validators=[routechoices.lib.validators.validate_corners_coordinates],
            ),
        ),
    ]
