# Generated by Django 2.1.5 on 2019-02-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20190203_2159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="map",
            field=models.ForeignKey(
                blank=True,
                help_text="Pick a map from the club organizing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.Map",
            ),
        ),
    ]
