# Generated by Django 2.1.5 on 2019-02-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190204_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Device'),
        ),
    ]
