# Generated by Django 4.0.3 on 2022-05-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_event_tail_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tail_length",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Default tail length when a user open the event. Can be overriden by the viewers in the event page settings tab.",
                verbose_name="Tail length (seconds)",
            ),
        ),
    ]
