# Generated by Django 4.0.4 on 2022-05-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_event_tail_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceownership",
            name="nickname",
            field=models.CharField(default="", max_length=8),
        ),
    ]
