# Generated by Django 4.0.4 on 2022-05-06 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def transfer_ownership(apps, schema_editor):

    # get BankAccounts model
    DeviceOwnership = apps.get_model("core", "DeviceOwnership")
    DeviceClubOwnership = apps.get_model("core", "DeviceClubOwnership")

    for do in DeviceOwnership.objects.all():
        # print user object
        print(do.device.aid)
        print(do.user.username)
        for club in do.user.club_set.all():
            print(club.name)
            DeviceClubOwnership.objects.get_or_create(
                device=do.device,
                club=club,
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0011_deviceownership_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceClubOwnership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("nickname", models.CharField(default="", max_length=8)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_ownerships",
                        to="core.club",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_ownerships",
                        to="core.device",
                    ),
                ),
            ],
            options={
                "unique_together": {("device", "club")},
            },
        ),
        migrations.RunPython(transfer_ownership),
    ]
