# Generated by Django 2.1.7 on 2019-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start time (UTC)'),
        ),
    ]
