# Generated by Django 2.1.7 on 2019-05-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190326_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='open_registration',
            field=models.BooleanField(default=False, help_text='Participant can register themselves to the event through a webpage.'),
        ),
    ]
