# Generated by Django 4.0.4 on 2022-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_deviceclubownership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="owners",
            field=models.ManyToManyField(
                related_name="devices",
                through="core.DeviceClubOwnership",
                to="core.club",
            ),
        ),
        migrations.DeleteModel(
            name="DeviceOwnership",
        ),
    ]
