# Generated by Django 4.0.4 on 2022-05-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_device_owners_delete_deviceownership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceclubownership",
            name="nickname",
            field=models.CharField(default="", max_length=12),
        ),
    ]
