# Generated by Django 4.0.4 on 2022-05-25 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_deviceclubownership_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deviceclubownership",
            options={
                "verbose_name": "Device ownership",
                "verbose_name_plural": "Device ownerships",
            },
        ),
    ]
