# Generated by Django 2.2.2 on 2019-06-07 18:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20190607_1525'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deviceownership',
            unique_together={('device', 'user')},
        ),
    ]
