# Generated by Django 4.0.4 on 2022-06-09 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_device_battery_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(
                blank=True,
                default="# GPS tracking powered by routechoices.com\n\nBrowse our events here.",
                help_text="This text will be displayed on the club site frontpage, use markdown formatting",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="map_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Leave blank if not using extra maps",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="send_interval",
            field=models.PositiveIntegerField(
                default=5,
                help_text="If using dedicated trackers, enter here the sending interval set for the devices to, if using the official smartphone app leave the value at 5 seconds",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Send interval (seconds)",
            ),
        ),
    ]
