# Generated by Django 4.0.3 on 2022-07-07 12:48

from django.db import migrations

import routechoices.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_club_description_alter_event_map_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="backdrop_map",
            field=routechoices.core.models.BackroundMapChoicesField(
                default="blank", max_length=16
            ),
        ),
    ]
