# Generated by Django 3.1.2 on 2020-10-01 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auto_20201001_0710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imeidevice",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="physical_device",
                to="core.device",
            ),
        ),
    ]
