# Generated by Django 4.1rc1 on 2022-08-04 03:25

from operator import itemgetter

import gps_encoding
import orjson as json
from django.db import migrations, models

from routechoices.lib.helpers import epoch_to_datetime


def transfer_data(apps, schema_editor):

    # get BankAccounts model
    Device = apps.get_model("core", "Device")

    for d in Device.objects.all():
        try:
            locs_dict = json.loads(d.locations_raw)
        except Exception:
            locs_dict = {"timestamps": [], "latitudes": [], "longitudes": []}
        locs = zip(
            locs_dict["timestamps"], locs_dict["latitudes"], locs_dict["longitudes"]
        )
        locs = list(sorted(locs, key=itemgetter(0)))
        d.locations_encoded = gps_encoding.encode_data(locs)
        try:
            d._locations_count = len(locs_dict["timestamps"])
        except Exception:
            d._locations_count = 0
        if d._locations_count > 0:
            last_loc = locs[-1]
            d._last_location_datetime = epoch_to_datetime(last_loc[0])
            d._last_location_latitude = last_loc[1]
            d._last_location_longitude = last_loc[2]
        d.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_club_analytics_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="_last_location_datetime",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="_last_location_latitude",
            field=models.DecimalField(
                decimal_places=5, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="_last_location_longitude",
            field=models.DecimalField(
                decimal_places=5, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="_locations_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="device",
            name="locations_encoded",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
    ]
