# Generated by Django 4.1rc1 on 2022-08-04 03:25

from django.db import migrations, models


def transfer_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_club_analytics_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="_last_location_datetime",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="_last_location_latitude",
            field=models.DecimalField(
                decimal_places=5, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="_last_location_longitude",
            field=models.DecimalField(
                decimal_places=5, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="_locations_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="device",
            name="locations_encoded",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
    ]
