# Generated by Django 4.1 on 2022-08-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_device__last_location_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="locations_raw",
        ),
    ]
