# Generated by Django 4.1 on 2022-08-06 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_remove_device_locations_raw"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="_locations_count",
            new_name="_location_count",
        ),
    ]
