# Generated by Django 4.1 on 2022-08-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_tcpdevicecommand_delete_queclinkcommand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tcpdevicecommand",
            options={
                "ordering": ["-modification_date"],
                "verbose_name": "TCP Device command",
                "verbose_name_plural": "TCP Devices commands",
            },
        ),
    ]
