# Generated by Django 3.1.4 on 2021-02-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20210206_0815"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="map_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Leave blank if you are not using extra maps",
                max_length=255,
            ),
        ),
    ]
