# Generated by Django 4.1 on 2022-08-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_tcpdevicecommand_device_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="_last_location_datetime",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="_last_location_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=5, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="_last_location_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=5, editable=False, max_digits=10, null=True
            ),
        ),
    ]
