# Generated by Django 3.1.4 on 2021-02-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_event_map_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mapassignation",
            unique_together={("map", "event"), ("event", "title")},
        ),
    ]
