# Generated by Django 4.1 on 2022-08-24 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_device__last_location_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="allow_live_chat",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
