# Generated by Django 3.1.4 on 2021-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_auto_20210303_1738"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="text",
            field=models.CharField(
                blank=True,
                help_text="Optional text that will be displayed on the event page",
                max_length=280,
            ),
        ),
    ]
