# Generated by Django 4.1 on 2022-08-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_remove_event_allow_live_chat_delete_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(
                blank=True,
                default=(
                    "## Live GPS Tracking\n\n"
                    "Follow our events live or replay them later.\n\n"
                    "*This website is powered by Routechoices.com*"
                ),
                help_text=(
                    "This text will be displayed on the club site frontpage,"
                    " use markdown formatting"
                ),
            ),
        ),
    ]
