# Generated by Django 3.2.4 on 2021-06-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_club_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='free_plan_events_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
