# Generated by Django 3.2.4 on 2021-07-13 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_auto_20210713_0531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.club",
                verbose_name="Club (*)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name (*)"),
        ),
    ]
