# Generated by Django 4.1.2 on 2022-11-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_eventset_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.eventset",
                verbose_name="Event Set",
            ),
        ),
    ]
