# Generated by Django 4.1.2 on 2022-11-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_event_event_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="emergency_contact",
            field=models.EmailField(
                blank=True,
                help_text="Email address of a person available to respond in the case a competitor carrying a GPS tracker with SOS feature enabled triggers the SOS button.",
                max_length=254,
                null=True,
            ),
        ),
    ]
