# Generated by Django 4.1.4 on 2022-12-20 10:44
import zstd
from django.db import migrations, models

from routechoices.core.models import Device


def transfer_data(apps, schema_editor):
    for dev in Device.objects.exclude(locations_encoded=""):
        dev.locations_encoded_compressed = zstd.compress(dev.locations_encoded.encode())
        dev.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_event_emergency_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="locations_encoded_compressed",
            field=models.BinaryField(blank=True, default=b""),
        ),
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
    ]
