# Generated by Django 4.1.4 on 2022-12-20 10:44
from django.db import migrations, models


def transfer_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_event_emergency_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="locations_encoded_compressed",
            field=models.BinaryField(blank=True, default=b""),
        ),
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
    ]
