# Generated by Django 4.1.4 on 2023-01-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_event_emergency_contact"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("club", "slug"), ("club", "event_set", "name")},
        ),
    ]
