# Generated by Django 4.1.4 on 2023-01-13 06:33
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_event_emergency_contact"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("club", "event_set", "name"), ("club", "slug")},
        ),
    ]
