# Generated by Django 3.2.4 on 2021-07-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_event_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='route',
        ),
    ]
