# Generated by Django 4.1.4 on 2022-12-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_device_locations_encoded_compressed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="locations_encoded",
        ),
    ]
