# Generated by Django 4.1.4 on 2022-12-20 13:02
import zstd
from django.db import migrations, models

from routechoices.core.models import Device


def transfer_data(apps, schema_editor):
    for d in Device.objects.all():
        d.locations_encoded = (
            zstd.uncompress(bytes(d.locations_encoded_compressed)).decode()
            if d.locations_encoded_compressed
            else ""
        )
        d.update_cached_data()
        d.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_remove_device_locations_encoded"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="locations_encoded",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
    ]
