# Generated by Django 3.2.4 on 2021-07-13 07:56

from django.db import migrations, models
import django.db.models.deletion
import routechoices.lib.helpers
import routechoices.lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_event_backdrop_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.club",
                verbose_name="Club",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(verbose_name="End Date (UTC)"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.CharField(
                db_index=True,
                default=routechoices.lib.helpers.short_random_slug,
                help_text="This is used to build the url of this event",
                max_length=50,
                validators=[routechoices.lib.validators.validate_nice_slug],
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(verbose_name="Start Date (UTC)"),
        ),
    ]
