# Generated by Django 4.1.5 on 2023-01-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_event_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="core.eventset",
                verbose_name="Event Set",
            ),
        ),
    ]
