# Generated by Django 3.2.5 on 2021-07-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_club_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
