# Generated by Django 3.2.5 on 2021-07-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210604_0958'),
        ('core', '0039_alter_club_slug'),
    ]

    operations = [
    ]
