# Generated by Django 4.2rc1 on 2023-03-31 14:33

from django.db import migrations, models

import routechoices.lib.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_event_event_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="slug_changed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="slug_changed_from",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=50,
                null=True,
                validators=[routechoices.lib.validators.validate_domain_slug],
            ),
        ),
    ]
