# Generated by Django 4.1.2 on 2023-03-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_event_event_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_set",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Events within the same event set will be grouped "
                    "together on the event listing page."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="core.eventset",
                verbose_name="Event Set",
            ),
        ),
    ]
