# Generated by Django 3.2.5 on 2021-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_device_modification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
