# Generated by Django 4.2 on 2023-04-05 04:37

from django.db import migrations, models

import routechoices.lib.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_club_slug_changed_at_club_slug_changed_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventset",
            name="list_secret_events",
            field=models.BooleanField(
                default=False,
                help_text="Wether secret event are listed in the event set page",
            ),
        ),
        migrations.AddField(
            model_name="eventset",
            name="slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="This is used to build the url of this event set page",
                max_length=50,
                null=True,
                validators=[routechoices.lib.validators.validate_nice_slug],
                verbose_name="Slug",
            ),
        ),
    ]
