# Generated by Django 4.2 on 2023-04-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_eventset_list_secret_events_eventset_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventset",
            name="list_secret_events",
            field=models.BooleanField(
                default=False,
                help_text="Wether secret events are listed in the event set page",
            ),
        ),
    ]
