# Generated by Django 4.2 on 2023-04-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_eventset_list_secret_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventset",
            name="create_page",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether a page with all the events of the set will be generated"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="eventset",
            name="list_secret_events",
            field=models.BooleanField(
                default=False,
                help_text="Whether secret events are listed in the event set page",
            ),
        ),
    ]
