# Generated by Django 4.2 on 2023-04-05 09:16

from django.db import migrations, models

import routechoices.lib.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_eventset_create_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventset",
            name="list_secret_events",
            field=models.BooleanField(
                default=False,
                help_text="Whether the page lists the secret events of the event set",
            ),
        ),
        migrations.AlterField(
            model_name="eventset",
            name="slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="This is used to build the url of the page",
                max_length=50,
                null=True,
                validators=[routechoices.lib.validators.validate_nice_slug],
                verbose_name="Slug",
            ),
        ),
    ]
