# Generated by Django 3.2.6 on 2021-08-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_event_backdrop_map"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-start_date", "name"],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
