# Generated by Django 4.2 on 2023-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_alter_eventset_list_secret_events_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="upgraded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="club",
            name="upgraded_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
