# Generated by Django 4.2 on 2023-05-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_club_upgraded_club_upgraded_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="order_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
