# Generated by Django 3.2.7 on 2021-09-20 16:22

from django.db import migrations, models
import django.db.models.deletion
import routechoices.lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_event_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SpotDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('messenger_id', models.CharField(max_length=32, unique=True, validators=[routechoices.lib.validators.validate_esn])),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spot_device', to='core.device')),
            ],
            options={
                'verbose_name': 'spot device',
                'verbose_name_plural': 'spot devices',
                'ordering': ['messenger_id'],
            },
        ),
    ]
