# Generated by Django 3.2.7 on 2021-09-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_spotdevice_spotfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotfeed',
            name='feed_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
