# Generated by Django 4.2.2 on 2023-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_alter_club_order_id_alter_club_slug_changed_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventset",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "This text will be displayed on the event set page"
                    ", use markdown formatting"
                ),
            ),
        ),
    ]
