# Generated by Django 3.2.7 on 2021-09-21 16:21

import django.core.validators
from django.db import migrations, models
import re
import routechoices.lib.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_spotfeed_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='aid',
            field=models.CharField(default=routechoices.lib.helpers.random_device_id, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
