# Generated by Django 4.2.2 on 2023-08-14 13:50

from django.db import migrations, models

import routechoices.core.models
import routechoices.lib.storages


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_eventset_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Image of size greater or equal than 1200x630 pixels",
                null=True,
                storage=routechoices.lib.storages.OverwriteImageStorage(
                    aws_s3_bucket_name="routechoices"
                ),
                upload_to=routechoices.core.models.banner_upload_path,
            ),
        ),
    ]
