# Generated by Django 3.2.7 on 2021-10-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20211006_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='username',
            new_name='nickname',
        ),
    ]
