# Generated by Django 4.2.2 on 2023-08-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_club_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualDonator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("upgraded", models.BooleanField(default=False)),
                ("upgraded_date", models.DateTimeField(blank=True, null=True)),
                ("order_id", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
    ]
