# Generated by Django 4.0rc1 on 2021-11-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_alter_event_backdrop_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="extra_maps",
            field=models.ManyToManyField(
                related_name="+", through="core.MapAssignation", to="core.Map"
            ),
        ),
    ]
