# Generated by Django 5.0 on 2023-12-04 16:16

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_alter_event_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="duration",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("end_date"), "-", models.F("start_date")
                ),
                output_field=models.DurationField(),
            ),
        ),
    ]
