# Generated by Django 5.0 on 2023-12-04 18:01

import re

import django.core.validators
from django.db import migrations, models

import routechoices.lib.helpers


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_event_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="aid",
            field=models.CharField(
                db_index=True,
                default=routechoices.lib.helpers.random_key,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="aid",
            field=models.CharField(
                db_index=True,
                default=routechoices.lib.helpers.random_key,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="aid",
            field=models.CharField(
                db_index=True,
                default=routechoices.lib.helpers.random_device_id,
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="aid",
            field=models.CharField(
                db_index=True,
                default=routechoices.lib.helpers.random_key,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventset",
            name="aid",
            field=models.CharField(
                db_index=True,
                default=routechoices.lib.helpers.random_key,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="aid",
            field=models.CharField(
                db_index=True,
                default=routechoices.lib.helpers.random_key,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
    ]
