# Generated by Django 4.0 on 2021-12-23 08:27

from django.db import migrations, models
import routechoices.lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_event_extra_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.CharField(help_text='.routechoices.com', max_length=50, unique=True, validators=[routechoices.lib.validators.validate_domain_slug]),
        ),
    ]
