# Generated by Django 5.0 on 2023-12-05 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_alter_club_aid_alter_competitor_aid_alter_device_aid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="duration",
        ),
    ]
