# Generated by Django 5.0 on 2023-12-29 16:22

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_remove_event_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                django.db.models.functions.text.Upper("slug"),
                name="rc_event_slug_upper_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                django.db.models.functions.text.Upper("slug_changed_from"),
                models.OrderBy(models.F("slug_changed_at"), descending=True),
                name="rc_event_changed_slug_idx",
            ),
        ),
    ]
