# Generated by Django 5.0 on 2023-12-29 17:01

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import routechoices.lib.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_club_rc_event_slug_upper_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="club",
            new_name="core_club_slug_upper_idx",
            old_name="rc_event_slug_upper_idx",
        ),
        migrations.RenameIndex(
            model_name="club",
            new_name="core_club_changed_slug_idx",
            old_name="rc_event_changed_slug_idx",
        ),
        migrations.AlterField(
            model_name="imeidevice",
            name="imei",
            field=models.CharField(
                db_index=True,
                max_length=32,
                unique=True,
                validators=[routechoices.lib.validators.validate_imei],
            ),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                django.db.models.functions.text.Upper("domain"),
                name="core_club_domain_upper_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                django.db.models.functions.text.Upper("slug"),
                name="core_event_slug_upper_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                models.F("privacy"),
                models.F("list_on_routechoices_com"),
                models.F("end_date"),
                models.F("event_set_id"),
                name="core_event_list_frontpage_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                models.F("privacy"),
                models.F("club_id"),
                models.F("end_date"),
                models.F("event_set_id"),
                name="core_event_list_clubpage_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                models.F("privacy"),
                models.F("list_on_routechoices_com"),
                models.F("end_date"),
                name="core_event_listing_idx",
            ),
        ),
    ]
