# Generated by Django 4.0.1 on 2022-01-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_club_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
