# Generated by Django 5.0.1 on 2024-01-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0061_rename_rc_event_slug_upper_idx_core_club_slug_upper_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="forbid_invite_request",
            field=models.BooleanField(
                default=False,
                verbose_name="Prevent external users to request admin rights",
            ),
        ),
    ]
