# Generated by Django 5.0.1 on 2024-03-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_alter_mapassignation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tcpdevicecommand",
            name="comment",
            field=models.CharField(blank=True, default=""),
        ),
    ]
