# Generated by Django 5.0.4 on 2024-05-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_tcpdevicecommand_comment"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="core_event_list_frontpage_idx",
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="core_event_listing_idx",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="list_on_routechoices_com",
            new_name="on_events_page",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                models.F("privacy"),
                models.F("on_events_page"),
                models.F("end_date"),
                models.F("event_set_id"),
                name="core_event_list_frontpage_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                models.F("privacy"),
                models.F("on_events_page"),
                models.F("end_date"),
                name="core_event_listing_idx",
            ),
        ),
    ]
