# Generated by Django 5.0.4 on 2024-05-17 14:39

from django.db import migrations, models
from django.db.models import F

from routechoices.core.models import Event


def transfer_data(apps, schema_editor):
    events = Event.objects.exclude(emergency_contact__isnull=True).exclude(
        emergency_contact=""
    )
    events.update(emergency_contacts=F("emergency_contact"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_remove_event_core_event_list_frontpage_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="emergency_contacts",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Email addresses of people that will be contacted if a runner carrying a GPS tracker triggers an SOS signal. (Specific device enabled feature)",
            ),
        ),
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
    ]
