# Generated by Django 5.0.4 on 2024-05-17 14:50

from django.db import migrations, models

import routechoices.lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_event_emergency_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="emergency_contact",
        ),
        migrations.AlterField(
            model_name="event",
            name="emergency_contacts",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Email addresses of people that will be contacted if a runner carrying a GPS tracker triggers an SOS signal. (Device specific feature)",
                validators=[routechoices.lib.validators.validate_emails],
            ),
        ),
    ]
