# Generated by Django 5.0.4 on 2024-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_club_o_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="frontpage_featured",
            field=models.BooleanField(
                default=False, verbose_name="Featured on frontpage"
            ),
        ),
    ]
