# Generated by Django 5.0.4 on 2024-05-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_club_frontpage_featured"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IndividualDonator",
        ),
    ]
