# Generated by Django 5.1 on 2024-08-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_alter_frontpagefeedback_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frontpagefeedback",
            name="content",
            field=models.TextField(),
        ),
    ]
