# Generated by Django 5.0.4 on 2024-05-17 14:39

# import re

from django.conf import settings
from django.db import migrations

# from routechoices.core.models import Club, Map
# from routechoices.lib.s3 import s3_rename_object


def transfer_data(apps, schema_editor):
    # clubs = Club.objects.all()
    # for club in clubs:
    #     if club.logo:
    #         old_name = club.logo.name
    #         if re.match(r"[a-z]", old_name[6]) or re.match(r"[a-z]", old_name[8]):
    #             new_name = f"logos/{old_name[6:9].upper()}{old_name[9:]}"
    #             print(f"{old_name} -> {new_name}")
    #             s3_rename_object(settings.AWS_S3_BUCKET, old_name, new_name)
    #             club.logo.name = new_name
    #             club.save()
    #     if club.banner:
    #         old_name = club.banner.name
    #         if re.match(r"[a-z]", old_name[8]) or re.match(r"[a-z]", old_name[10]):
    #             new_name = f"banners/{old_name[8:11].upper()}{old_name[11:]}"
    #             print(f"{old_name} -> {new_name}")
    #             s3_rename_object(settings.AWS_S3_BUCKET, old_name, new_name)
    #             club.banner.name = new_name
    #             club.save()

    # maps = Map.objects.all()
    # for rmap in maps:
    #     old_name = rmap.image.name
    #     if re.match(r"[a-z]", old_name[5]) or re.match(r"[a-z]", old_name[7]):
    #         new_name = f"maps/{old_name[5:8].upper()}{old_name[8:]}"
    #         print(f"{old_name} -> {new_name}")
    #         s3_rename_object(settings.AWS_S3_BUCKET, old_name, new_name)
    #         rmap.image.name = new_name
    #         rmap.save()
    pass

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_alter_frontpagefeedback_content"),
    ]

    operations = [
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
    ]
