# Generated by Django 5.1.1 on 2024-09-30 10:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_competitor_user_usersetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSetting',
            new_name='UserSettings',
        ),
    ]
