# Generated by Django 5.2.16 on 2026-08-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0119_add_order_number_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventset",
            name="external_metadata",
            field=models.JSONField(editable=False, null=True),
        ),
    ]
