# Generated by Django 5.2.17 on 2026-09-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_alter_deviceclubownership_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="third_party_oauth_credentials",
            field=models.JSONField(default=dict),
        ),
    ]
