# Generated by Django 5.2.17 on 2026-09-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_eventset_external_metadata"),
        ("core", "0121_usersettings_third_party_oauth_credentials"),
    ]

    operations = []
